### ISSUE TITLE
install mb_url

### ISSUE THREAD

**Issue by JulienBuonarota** [dochang/mb-url#1]
Hello,
I m not sure this is the place for my question.
I want to use the mb-url package because i have problems with doi-utils and it seems to be related
to the fact that it tries to connect to an https through a proxy.
I installed mb-url with MELPA which proceeded without any errors.
Nevertheless i do not understand how to use mb-url.
I would normaly try to load it, "M-x mb-rul" or simply put (require 'mb-url) in my config file but mb-url does not exist for my emacs and both commands return an error.
How do i proceed to make emacs use mb-url.

**Comment by dochang** [comment]
Thank you for your feedback!

To use mb-url, you need: 1. install an advice on `url-http`.  2. bind `mb-url-http-backend` to a backend.

To install the advice, put the following sexp in your init file:

```
(advice-add 'url-http :around 'mb-url-http-around-advice)
```

If `mb-url-http-backend` is `nil`, it means no backend, use the built in `url-http` instead.  So if you want to use curl backend, put this in your init file:

```
(setq mb-url-http-backend 'mb-url-http-curl)
```

**Comment by dochang** [comment]
The purpose of mb-url is that make `url-retrieve` use external processes to download files in Emacs.

So the backends are external programs or daemons outside Emacs.

Currently there are curl and httpie backends.  You need to install one of them manually.

To install curl, see https://curl.haxx.se/download.html .

To install httpie, see https://httpie.org/doc#installation .

**Comment by JulienBuonarota** [comment]
Thank you.
I am at work and it is difficult to install curl. I come back to you when it is down and let you know the final word about my problem.
Best regards.
